### PR TITLE
Fixed generating a single `<name>.proto` for a Protobuf package that is composed of many `*.proto` files

### PR DESCRIPTION
**Pull request by maoueh**
In our project, we have multiple source files that all map to the same Protobuf package. For example:

- `proto/sf/substreams/v1`
  - `modules.proto`
  - `clock.proto`
  - `substreams.proto`

When using `proto-gen-prost` with:

```
protoc -I./proto --prost_out=src/pb sf/substreams/v1/substreams.proto
```

The plugin was actually exiting with a 0 exit code but no files was generated. The reason this is happening because `entry.with_output_filename(filename)` call is made only when creating the initial entry for a package, which fails if the very first file that is creating the entry (https://github.com/neoeinstein/protoc-gen-prost/blob/fe8e21a9d319c305cda0cfddd146ccddc73d36dd/protoc-gen-prost/src/lib.rs#L80-L90) is not the actual files passed to `protoc` binary.

To fix this, the condition that sets the actual `output_filename` is now check on every files that is part of a module which fixes the problem when the file to be generated is not the first file in the module's source proto files.

### CODE REVIEW

**Comment by neoeinstein** [comment]
I plan to review and get this merged this weekend, with a release of the updated generators early next week.

**Comment by neoeinstein** [comment]
This may need a bit more adjustment before I can merge it in. I _was_ able to reproduce the issue, but as the PR currently proposes, it produces types for proto files that weren't specified in the `protoc` invocation, but are imported/depended on.

As it stands, the plugins expect to receive all the proto files for a given package to be fed to it at the same time, and it does not produce definitions for messages and enums from imported files.

This leads me to a few questions that might highlight something I'm missing in reviewing this:

* Is there a reason that you would be providing only one proto file to the `protoc` invocation at a time?
* Does `substreams.proto` rely upon the types in `clock.proto` and `modules.proto`?
* Are you expecting that the types defined in `clock.proto` and `modules.proto` are output, even if only including `substreams.proto` or just that they are left unbound (to be provided by some later process)?

**Comment by neoeinstein** [comment]
Closing this for inactivity. If this is still an issue and you have some responses to the above questions, I'd be happy to look into this again.

**Comment by maoueh** [comment]
@neoeinstein Sorry did not had the time to resume this, but I will definitely come back and ping you when I gather all the required information.

**Pull request closed without merging**
