### PR TITLE
Bump `prost*` to 0.13.1, `pbjson` to 0.7.0 and `tonic*` to 0.12.0

### PR DESCRIPTION
**Pull request by mbrobbel**
`prost*` to 0.13.1
`pbjson` to 0.7.0
`tonic*` to 0.12.0

~This needs https://github.com/hyperium/tonic/pull/1785.~

### CODE REVIEW

**Comment by fenollp** [comment]
@neoeinstein Anything we can do to help move this forward? Thanks

**Comment by neoeinstein** [comment]
We'll need `tonic` to accept their PR and release a new version first. Once that's done, I can evaluate and get this in. As a general rule, though, this all looks good. I might also want to get `heck` up to `0.5.0` in `protoc-gen-tonic` so that the version matches what `tonic` uses itself. I'll be taking some vacation time over the next two weeks, so there may be a bit of a delay to full release until then if the `tonic` part goes into that timeframe.

**Comment by mbrobbel** [comment]
> Edit: It's possible that we can use a new-type pattern to implement these traits ourselves. If I have some time today or tomorrow, I'll take a swing through and see if I can update this to work with the released versions.

Updated the PR so that it works without the open tonic PR.

**Comment by fenollp** [comment]
@mbrobbel Looks like there's a CI issue with `pbjson-types`?

**Comment by mbrobbel** [comment]
@neoeinstein this is ready for another review.

**Comment by sept-en** [comment]
Hey @neoeinstein!
I'm reaching out about this open PR. I'm interested in the changes it proposes (bumping up `prost` specifically), and it would be great to see them merged so they're accessible from the Buf CLI registry.

If you've had a chance to look it over, I'd appreciate it.
Thanks for your time, and thank you for actually building such a valuable and convenient plugin!

**Review by neoeinstein — APPROVED** [review]

**Pull request merged**
