### PR TITLE
protoc-gen-prost: fix empty buf with fd sets

### PR DESCRIPTION
**Pull request by gwik**
When prost decides that file is empty, it is omitted from the output.
However requiring file descriptor sets makes it required.

However the code is cumbersome, the best would probably be to make `tokio/prost-build`'s `generate` to return an `Hash<Module, Option<FileDescriptorProto>>` but that would be a breaking change.
Maybe we can add a variant of the same method.

### CODE REVIEW

**Comment by gwik** [comment]
https://github.com/neoeinstein/protoc-gen-prost/issues/59

**Comment by fenollp** [comment]
This solves #59 for us! Would love to see this issue closed :)

**Comment by daviddomkar** [comment]
I am also waiting for this. Would also love to see this finally resolved.

**Comment by fenollp** [comment]
@neoeinstein I'd like to help getting this merged :)

**Pull request merged**
